name: Tag New Version and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag-and-release:
    uses: George-Ogden/actions/.github/workflows/python-release.yaml@v4.3.0
    with:
      validation-code: "from dynamic_type_checker import check_type; from typing import Literal; check_type(Literal[4], 4)"
